#include "Common.ush"
#include "SceneTextureParameters.ush"

Texture2D TestTexture;
SamplerState TestTextureSampler;
float4 SimpleColor;

void MainPS(
	float4 SvPosition : SV_POSITION,
    out float4 OutColor : SV_Target0
    )
{
	float2 BufferUV = SvPositionToBufferUV(SvPosition);
	//float2 BufferUV = float2(0.5f, 0.5f);
	float4 tex_color = TestTexture.SampleLevel(TestTextureSampler, BufferUV, 0);
    OutColor = SimpleColor * tex_color;
}